dist: trusty
language: python

python:
- "2.7"

before_install:
 - sudo apt install libboost-all-dev
 - sudo apt install libncurses5-dev
 - sudo apt-get install libboost-all-dev
 - sudo apt-get update

