dist: trusty

language: c++

compiler:
  - clang
  - gcc

before_install:
 - sudo apt install libboost-all-dev
 - sudo apt install libncurses5-dev
 - sudo apt-get install libboost-all-dev

 
install:
 - cd ./Control/Linux/build_Framework
 - make all
 - cd ../../../

 - cd ./IMU/serial
 - mkdir build
 - cd build
 - cmake ..
 - sudo make install

 - cd ../../../

 - mkdir build
 - cd build
 - cmake ../
 - make all
 - cd
